Feature/informational logging
test-editor/core-fixture pull request #48
Opened 2018-10-30 12:39 UTC by gunther-bachmann

2018-11-01 17:23 UTC, jjelschen requested changes

2018-11-02 08:36 UTC, kbayraktar requested changes

2018-11-02 08:36 UTC, kbayraktar commented on src/main/java/org/testeditor/fixture/core/DefaultLoggingListener.java
> +                JavaUnicodeEscaper.outsideOf(32, 0x7f)*/
is this line used ??

2018-11-02 09:08 UTC, kbayraktar commented
Please can you add these lines to build.gradle file:
```javascript
// For a summary of failed tests at the end of test execution.
tasks.withType(Test) {
    // a collection to track failedTests
    ext.failedTests = []
     afterTest { descriptor, result ->
        if (result.resultType == TestResult.ResultType.FAILURE) {
            String failedTest = "${descriptor.className}::${descriptor.name}"
            logger.debug("Adding " + failedTest + " to failedTests...")
            failedTests << [failedTest]
        }
    }
     afterSuite { suite, result ->
        if (!suite.parent) { // will match the outermost suite
            // logs each failed test
            if (!failedTests.empty) {
                logger.lifecycle("\n\n*************************************************************************************************")
                logger.lifecycle("\nFailed tests:")
                failedTests.each { failedTest ->
                    logger.lifecycle("${failedTest}")
                }
            }
            logger.lifecycle("\n*************************************************************************************************\n")
        }
    }
}
```

2018-11-05 09:31 UTC, jjelschen approved these changes

2018-11-05 12:24 UTC, merged